- name: Deploy Git, Docker, and Docker Compose
  hosts: 52.7.128.188
  become: yes
  tasks:
    - name: Update apt repository and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Install Git, Docker, and Compose
      apt:
        pkg:
          - git 
          - docker-compose
          - docker 

- name: Clone Git repository
  hosts: 18.206.236.239
  become: yes
  tasks:
    - name: Clone Git Repository
      git: repo=https://github.com/Rolly-M/LS-Lab_2.git dest=/home/ubuntu/LS-Lab_2

- name: Running the different containers
  hosts: 18.206.236.239
  become: yes
  tasks:
    - name: Stop previous container exixtence
      command: docker-compose -f /home/ubuntu/LS-Lab_2/docker-compose.yml down -v
      
    - name: Run Docker Compose
      command: docker-compose -f /home/ubuntu/LS-Lab_2/docker-compose.yml up --build -d